### ISSUE TITLE
Current install is broken, because latest apns2 (0.6.0) is incompatible

### ISSUE THREAD

**Issue by nuschk** [jazzband/django-push-notifications#515] opened 2019-08-14 13:58 UTC
The project doesn't work with the latest apns2 (0.6.0), which is installed, as per `setup.cfg`: `apns2>=0.3.0`.

APNS2 did some re-ordering of argument types on `payload.Payload` which leads to the following error:

```
>>> dev = APNSDevice.objects.get(pk=35934)
>>> dev.send_message(message="Blah")
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/project/env/lib/python3.6/site-packages/push_notifications/models.py", line 159, in send_message
    **kwargs
  File "/project/env/lib/python3.6/site-packages/push_notifications/apns.py", line 113, in apns_send_message
    certfile=certfile, **kwargs
  File "/project/env/lib/python3.6/site-packages/push_notifications/apns.py", line 90, in _apns_send
    data = _apns_prepare(registration_id, alert, **kwargs)
  File "/project/env/lib/python3.6/site-packages/push_notifications/apns.py", line 60, in _apns_prepare
    url_args, custom=extra, thread_id=thread_id)
TypeError: __init__() got multiple values for argument 'custom'
```

The resolution in this case is straight-forward. Either:

1) Don't install latest APNS2 (<= 0.5.0)
2) or use only named attributes for all attributes.

Thank you!

**Comment by odinuge** [comment] 2019-08-16 10:13
Duplicate of #513, closing in favor of that one.

**Closed by odinuge** 2019-08-16 10:13 UTC

**Comment by nuschk** [comment] 2019-08-16 11:21
Sorry, I didn't see that one. Thanks!
