### ISSUE TITLE
Incompatibility with Python version 3.5.2

### ISSUE THREAD

**Issue by Yaroslav-DDI** [jazzband/django-push-notifications#514] opened 2019-08-13 07:50 UTC
I used pyenv environment with the version of python 3.5.2 and got this error:

```
File ~/lib/python3.5/site-packages/push_notifications/apns.py", line 9, in <module>
    from apns2 import client as apns2_client
File "~/lib/python3.5/site-packages/apns2/client.py", line 9, in <module>
    from typing import Deque, Dict, Iterable, Optional, Tuple, Type, Union
ImportError: cannot import name 'Deque'

Process finished with exit code 0
```

from typing [docs](https://docs.python.org/3.5/library/typing.html#typing.Deque):
class typing.Deque - New in version 3.5.4.

from django-push-notifications [dependencies](https://github.com/jazzband/django-push-notifications#dependencies):
- Python 2.7 or 3.4+

**Comment by odinuge** [comment] 2019-08-16 10:12
Duplicate of #513, closing in favor of that one.

**Closed** 2019-08-16 10:13 UTC
